# vim:ft=kitty

## name:     Dark
## blurb:    Standard dark terminal palette

# The basic colors
foreground              #D3D7CF
background              #1A1A1A
selection_foreground    #1A1A1A
selection_background    #D3D7CF

# Cursor colors
cursor                  #D3D7CF
cursor_text_color       #1A1A1A

# URL underline color when hovering with mouse
url_color               #729FCF

# Kitty window border colors
active_border_color     #D3D7CF
inactive_border_color   #555555
bell_border_color       #FCE94F

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1A1A1A
active_tab_background   #D3D7CF
inactive_tab_foreground #D3D7CF
inactive_tab_background #2C2C2C
tab_bar_background      #121212

# Colors for marks (marked text in the terminal)
mark1_foreground #1A1A1A
mark1_background #D3D7CF
mark2_foreground #1A1A1A
mark2_background #AD7FA8
mark3_foreground #1A1A1A
mark3_background #34E2E2

# The 16 terminal colors

# black
color0 #2E3436
color8 #555753

# red
color1 #CC0000
color9 #EF2929

# green
color2  #4E9A06
color10 #8AE234

# yellow
color3  #C4A000
color11 #FCE94F

# blue
color4  #3465A4
color12 #729FCF

# magenta
color5  #75507B
color13 #AD7FA8

# cyan
color6  #06989A
color14 #34E2E2

# white
color7  #D3D7CF
color15 #EEEEEC
